[project]
name = "quickpasteassistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pyautogui>=0.9.54",
    "pyperclip>=1.9.0",
    "pyqt6>=6.9.1",
]
